apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - echo hello; sleep 3600
    image: busybox
    name: busybox
  - args:
    - /bin/sh
    - -c
    - echo hello; sleep 3600
    image: busybox
    name: busybox2

