apiVersion: v1
kind: Pod
metadata:
   name: my-args-pod
   namespace: sj
spec:
 containers:
 - name: myapp-container
   image: busybox
   command: ['echo']
   args: ['This is my custom arguemtn']
 restartPolicy: Never
