apiVersion: v1
kind: Pod
metadata:
  name: my-configmap-volume-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'echo $(cat /etc/config/myKey) && sleep 3600']
    volumeMounts:
    - name: my-volume
      mountPath: /etc/config
  volumes:
  - name: my-volume
    configMap:
      name: my-config-map
