apiVersion: v1
kind: Pod
metadata:
  name: my-configmap-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'echo $(MY_VAR) && sleep 3600']
    env:
    - name: MY_VAR
      valueFrom:
        configMapKeyRef:
           name: my-config-map
           key: myKey
