apiVersion: v1
kind: Pod
metadata:
  name: my-secret-app
spec:
  containers:
  - name: my-secret-app
    image: busybox
    command: ['sh', '-c', 'echo Hello, Kubernetes! && sleep 3600']
    env:
     - name: MY_PASSWORD
       valueFrom:
         secretKeyRef:
            name: my-secret
            key: myKey

