apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    env:
     - name: USERNAME
       valueFrom:
         secretKeyRef:
            name: mysecret2
            key: username
