apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/foo
  volumes:
    - name: secret-volume
      secret:
        secretName: mysecret2
