apiVersion: v1
kind: PersistentVolume
metadata:
   name: myvvolume
spec:
   accessModes:
   - ReadWriteOnce
   - ReadWriteOnce
   storageClassName: normal
   capacity:
     storage: 10Gi
   hostPath:
     path: /etc/foo
