apiVersion: v1
kind: Service
metadata:
   name: chartmuseum-nodeport
spec:
  type: NodePort
  selector:
     app: chartmuseum
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30085
    protocol: TCP
