apiVersion: v1
kind: PersistentVolume
metadata:
   name: charmuseum-pv
spec:
  capacity:
    storage: 10Gi
  storageClassName: local
  accessModes:
  - ReadWriteOnce
  hostPath:
     path: /etc/chartMuseum
